// Code generated by mockery v2.30.16. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Refund is an autogenerated mock type for the Refund type
type Refund struct {
	mock.Mock
}

// RefundTransaction provides a mock function with given fields: invoice, amount, reason
func (_m *Refund) RefundTransaction(invoice string, amount int64, reason string) error {
	ret := _m.Called(invoice, amount, reason)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int64, string) error); ok {
		r0 = rf(invoice, amount, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRefund creates a new instance of Refund. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRefund(t interface {
	mock.TestingT
	Cleanup(func())
}) *Refund {
	mock := &Refund{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
