// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// ReservationHandler is an autogenerated mock type for the ReservationHandler type
type ReservationHandler struct {
	mock.Mock
}

// MakeReservation provides a mock function with given fields:
func (_m *ReservationHandler) MakeReservation() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// NewReservationHandler creates a new instance of ReservationHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReservationHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReservationHandler {
	mock := &ReservationHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
