// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// VenueHandler is an autogenerated mock type for the VenueHandler type
type VenueHandler struct {
	mock.Mock
}

// SearchVenue provides a mock function with given fields:
func (_m *VenueHandler) SearchVenue() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// NewVenueHandler creates a new instance of VenueHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVenueHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *VenueHandler {
	mock := &VenueHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
