name: Deploy App to Server

on:
    push:
        branches:
            - main

jobs:
    docker:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/playgroundpro-api-images:latest

            - name: Connect to server using SSH
              uses: appleboy/ssh-action@v0.1.10
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.KEY }}
                  port: ${{ secrets.PORT }}
                  script: |
                      docker stop playgroundpro-api-v1
                      docker rm playgroundpro-api-v1
                      docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/playgroundpro-api-images:latest
                      docker pull ${{ secrets.DOCKERHUB_USERNAME }}/playgroundpro-api-images:latest
                      docker run -d -p 80:8080 -e JWT_KEY=${{ secrets.JWT_KEY }} \
                        -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
                        -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
                        -e DBUSER=${{ secrets.DBUSER }} \
                        -e DBPASS=${{ secrets.DBPASS }} \
                        -e DBHOST=${{ secrets.DBHOST }} \
                        -e DBPORT=${{ secrets.DBPORT }} \
                        -e DBNAME=${{ secrets.DBNAME }} \
                        -e EMAIL_SENDER_NAME=${{ secrets.EMAIL_SENDER_NAME }} \
                        -e EMAIL_SENDER_ADDRESS=${{ secrets.EMAIL_SENDER_ADDRESS }} \
                        -e EMAIL_SENDER_PASSWORD=${{ secrets.EMAIL_SENDER_PASSWORD }} \
                        -e REDIS_HOST=${{ secrets.REDIS_HOST }} \
                        -e REDIS_PORT=${{ secrets.REDIS_PORT }} \
                        -e REDIS_DATABASE=${{ secrets.REDIS_DATABASE }} \
                        -e REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} \
                        -e MIDTRANS_SERVERKEY=${{ secrets.MIDTRANS_SERVERKEY }} \
                        -e MIDTRANS_MERCHANT_ID=${{ secrets.MIDTRANS_MERCHANT_ID }} \
                        --name playgroundpro-api-v1 \
                        ${{ secrets.DOCKERHUB_USERNAME }}/playgroundpro-api-images:latest
